### ISSUE TITLE
Master - Active/Deactive action is not working in latest version

### ISSUE THREAD

**Issue by Anjali-Chandwani** [knovator/masters-admin#51]
**Describe the bug**
Master - Active/Deactive action is not working in latest version

**To Reproduce**
1. Go to 'Master'
2. Click on 'Active toogle'
3. See error

**Expected behavior**
It should change to active/deactive according to click 

**Screenshots**
![image](https://github.com/knovator/masters-admin/assets/51951996/4df1981e-bf99-40ff-88c5-6eef087e18b4)

**Comment by chavda-bhavik** [comment]
I tested package api calling, it's working properly, might be a backend issue with `middleware`.

**Comment by chavda-bhavik** [comment]
Fixed in version `masters-node@2.10` and `masters-admin@2.1.0`
